### ISSUE TITLE
Hexdocs link not working

### ISSUE THREAD

**Issue by ankush981** [scrogson/romeo#15]
The documentation link is not working. While I was able to download the documentation by searching for `romeo` on Hexdocs, the direct link (posted on Hexdocs as well the README: https://hexdocs.pm/romeo/extra-readme.html) doesn't work.

**Comment by jbr** [comment]
Seems like it's just the `extra-` prefix that's not working, https://hexdocs.pm/romeo/readme.html has current docs for 0.6.0

**Comment by ankush981** [comment]
Cool, thanks! I'm really thankful for Romeo. I was having a very hard time looking for an Elixir client. :sweat_smile:
