### ISSUE TITLE
Support TLS only connections

### ISSUE THREAD

**Issue by scrogson** [scrogson/romeo#2]
hedwig-im/hedwig#23

**Comment by arpunk** [comment]
FYI I'm able to connect via TLS using `hedwig_xmpp`

**Comment by awenger** [comment]
@arpunk what options did you set to get it working? I just tried to connect to a Server that requires TLS but doesn't support STARTTLS and it failed with romeo.

**Comment by scrogson** [comment]
fixed in #23
