### ISSUE TITLE
Real disconnect

### ISSUE THREAD

**Issue by maximvl** [scrogson/romeo#3]
Hi! I'm using Romeo for xmpp bot and it is done well, but I haven't figure out how to disconnect from server. As I see here https://github.com/scrogson/romeo/blob/master/lib/romeo/connection.ex#L92 the process will reconnect again and again. Is there a way to disconnect totally?

**Comment by scrogson** [comment]
Hi @maximvl, 

Sorry for the delay. I believe `close` is what you're looking for: https://github.com/scrogson/romeo/blob/master/lib/romeo/connection.ex#L73

`disconnect` is a callback for the `Connection` library.

Hope that helps and sorry for the confusion.
