### ISSUE TITLE
Accessing XML?

### ISSUE THREAD

**Issue by 9mm** [scrogson/romeo#40]
Hey, this is a super basic question, but I'm not super familiar with Elixir and Erlang yet.

How do I actually access the `message_type` part of the response below thats buried in the JSON. Parsing the JSON is easy but is there an easy way to get at that? I tried looking for some methods to convert xml to map but didnt see it

```
%Romeo.Stanza.Message{
  body: "",
  delayed?: false,
  from: nil,
  html: nil,
  id: "",
  to: nil,
  type: "normal",
  xml: {:xmlel, "message", [],
   [
     {:xmlel, "gcm",
      [{"xmlns", "google:mobile:data"}, {"xmlns:data", "google:mobile:data"}],
      [
        xmlcdata: "{\"message_type\":\"nack\",\"from\":\"00000000000:00000000000000000000000000000000000000000000000-00000000000000000000000000000000000000-00000000000000000000000000000000000000000000000000000\",\"message_id\":\"5feef900-1a19-43b7-b2ef-d3e3d7997620\",\"error\":\"BAD_REGISTRATION\",\"error_description\":\"\"}"
      ]}
   ]}
}
```

**Comment by 9mm** [comment]
I'm using `Connction.send` btw, if there is any way I can just access the raw XML that would also work. Because then I can just use sweet_xml and xpath.

Otherwise it seems weird to parse from XML to "xmlel" and then back to xml binary just to use xpath

**Comment by 9mm** [comment]
This is what I ended up doing but it seemed crazy :/

    import SweetXml

    resp = Romeo.Stanza.to_xml(stanza.xml)
           |> xpath(~x"//gcm/text()"S)
           |> Jason.decode

**Comment by scrogson** [comment]
Hey there! What you want are the functions in the `Romeo.XML` module: https://hexdocs.pm/romeo/Romeo.XML.html

Here is what you need:

```ex
resp =
  stanza.xml
  |> Romeo.XML.subelement("gcm")
  |> Romeo.XML.cdata()
  |> Jason.decode()
```

**Comment by 9mm** [comment]
awesome thank you!
