### ISSUE TITLE
Error while connecting to server

### ISSUE THREAD

**Issue by farao** [scrogson/romeo#7]
I tried to connect to my XMPP server (running Prosody) via romeo 0.5 and it failed with the following error:

`iex(5)> {:ok, pid} = Conn.start_link(opts)  
{:ok, #PID<0.195.0>}
iex(6)> 
19:06:58.679 [info]  Established connection to SERVERURL

19:06:58.680 [debug] [NAME@SERVERURL][OUTGOING] "<stream:stream to='SERVERURL' version='1.0' xml:lang='en' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'>"

19:06:58.727 [debug] [NAME@SERVERURL][INCOMING] {:xmlstreamstart, "stream:stream", [{"xmlns:stream", "http://etherx.jabber.org/streams"}, {"xmlns", "jabber:client"}, {"version", "1.0"}, {"from", "SERVERURL"}, {"id", "SOMEID"}, {"xml:lang", "en"}]}

19:07:03.730 [info]  Authenticating with PLAIN

19:07:03.730 [debug] [NAME@SERVERURL][OUTGOING] "<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>SOMESTRING==</auth>"

19:07:03.774 [debug] [NAME@SERVERURL][INCOMING] {:xmlel, "stream:features", [], [{:xmlel, "starttls", [{"xmlns", "urn:ietf:params:xml:ns:xmpp-tls"}], [{:xmlel, "required", [], []}]}]}
*\* (EXIT from #PID<0.182.0>) an exception was raised:
    *\* (CaseClauseError) no case clause matching: "stream:features"
        (romeo) lib/romeo/auth.ex:62: anonymous fn/2 in Romeo.Auth.success?/1
        (romeo) lib/romeo/auth.ex:32: Romeo.Auth.do_authenticate/2
        (romeo) lib/romeo/transports/tcp.ex:94: Romeo.Transports.TCP.authenticate/1
        (romeo) lib/romeo/transports/tcp.ex:54: Romeo.Transports.TCP.start_protocol/1
        (romeo) lib/romeo/connection.ex:84: Romeo.Connection.connect/2
        (connection) lib/connection.ex:623: Connection.enter_connect/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
`

opts was: [jid: "NAME@SERVERURL", password: "PASSWORD", nickname: "NICKNAME", require_tls: true]

Is this an error of romeo or did I somehow use it wrongly?

**Comment by farao** [comment]
Any idea?

**Comment by scrogson** [comment]
Hey there. Sorry, I'm unsure what exactly would be wrong. I have not used Prosody and only have connected to an ejabberd server. It appears that the server is not returning stream features after authenticating.

**Comment by dhanson358** [comment]
I am having the same issue attempting to connect to Hipchat Cloud using the Hedwig project (https://github.com/jwarlander/hedwig_hipchat).

**Comment by nTraum** [comment]
I experience the same issue as @dhanson358 on Hipchat Cloud. I'm in no means an expert in XMPP, but   could this be related to XMPP's stream management extension? http://xmpp.org/extensions/xep-0198.html

Happy to provide more details if needed.

**Comment by scrogson** [comment]
Thanks for the reports. I'd love to solve this. However, I do not have a hipchat account, so some help here would be awesome.

I won't be able to put efforts into this for a couple of weeks.

**Comment by scrogson** [comment]
Hello all, please give master a try and report back. I ended up creating a free HipChat account and could see the issue was that the opening stream and stream features were being sent together in one parse step...so there was a `{: xmlstreamelement, stanza}` message for the `"stream:features"` in the mailbox of the process.

Thanks again for the report!

**Comment by dhanson358** [comment]
I can confirm that this now works for me just fine!  Thanks!
