### ISSUE TITLE
Create room and set it's configuration

### ISSUE THREAD

**Issue by burmajam** [scrogson/romeo#8]
Is there a way to create groupchat room and set it's configuration? I've created one using Hedwig but can't send message because room is locked. I guess it needs configuration set first. Also I'm interested how to invite users to that room? I couldn't find it in source but maybe I'm missing something.

Thanks

**Comment by scrogson** [comment]
@burmajam there is currently not any support for configuring a room or inviting directly with Romeo. You can certainly build out the required XML to send to the server with the functions provided in the `Romeo.XML` module.

I personally have never needed either of these yet so I have not added it here. So PRs welcome :wink:
