### ISSUE TITLE
FunXMPP support

### ISSUE THREAD

**Issue by bamorim** [scrogson/romeo#9]
I'm not a XMPP expert, I'm just learning right now.
Recently, I've been doing research on creating alternative Whatsapp clients and discovered they use a modified XMPP called FunXMPP, which is basically a modified XMPP where instead of using raw ASCII XML they replace some keywords by single bytes and represent xml structures using lists of lists.

Given that, I'd guess that is not completely impossible to implement some middleware to adapt Romeo to FunXMPP. I'm willing to contribute with that but don't know much about it right now.

Do you think it is viable to implement that here and if I do so, are you willing to merge it?

(I'm also accepting directions to which modules I should be looking to add support to FunXMPP, hahaha)

**Comment by scrogson** [comment]
Hi there @bamorim, that sounds interesting. I have not yet looked into FunXMPP so I can't offer any direction there :smile:

I'll look into it and see if I can offer you some help.

**Comment by bamorim** [comment]
@scrogson You can take a look here: https://github.com/mgp25/Chat-API/wiki/FunXMPP-Protocol

Probably we just need to transform the binary format into XML when receiving stanzas and from XML to the binary format when sending. Something just on the top of the transport layer (an optional layer so people can connect to whatsapp). I just need a clue how to do it. I see you are using fxml_stream, so probably somewhere there, but I still have to look at the docs.

**Comment by scrogson** [comment]
@bamorim I'm closing this for now as I will probably not be implementing this anytime soon. Thanks for bringing it to my attention.
